export const productionsConstants = {
    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'PRODUCTIONS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PRODUCTIONS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PRODUCTIONS_GETALL_FAILURE',

    GET_REQUEST: 'PRODUCTIONS_GET_REQUEST',
    GET_SUCCESS: 'PRODUCTIONS_GET_SUCCESS',
    GET_FAILURE: 'PRODUCTIONS_GET_FAILURE',  

    ADD_REQUEST: 'PRODUCTIONS_ADD_REQUEST',
    ADD_SUCCESS: 'PRODUCTIONS_ADD_SUCCESS',
    ADD_FAILURE: 'PRODUCTIONS_ADD_FAILURE',
    
    UPDATE_REQUEST: 'PRODUCTIONS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'PRODUCTIONS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'PRODUCTIONS_UPDATE_FAILURE',    

    DELETE_REQUEST: 'PRODUCTIONS_DELETE_REQUEST',
    DELETE_SUCCESS: 'PRODUCTIONS_DELETE_SUCCESS',
    DELETE_FAILURE: 'PRODUCTIONS_DELETE_FAILURE',

};
