export const companyConstants = {

    ADD_REQUEST: 'COMPANY_ADD_REQUEST',
    ADD_SUCCESS: 'COMPANY_ADD_SUCCESS',
    ADD_FAILURE: 'COMPANY_ADD_FAILURE',

    REGISTER_REQUEST: 'COMPANY_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'COMPANY_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'COMPANY_REGISTER_FAILURE',

    GET_REQUEST: 'COMPANY_GET_REQUEST',
    GET_SUCCESS: 'COMPANY_GET_SUCCESS',
    GET_FAILURE: 'COMPANY_GET_FAILURE',

    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
