export const teamConstants = {
    ADD_REQUEST: 'TEAM_ADD_REQUEST',
    ADD_SUCCESS: 'TEAM_ADD_SUCCESS',
    ADD_FAILURE: 'TEAM_ADD_FAILURE',

    // LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    // LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    // LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    // LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'TEAM_GETALL_REQUEST',
    GETALL_SUCCESS: 'TEAM_GETALL_SUCCESS',
    GETALL_FAILURE: 'TEAM_GETALL_FAILURE',

    GET_REQUEST: 'TEAM_GET_REQUEST',
    GET_SUCCESS: 'TEAM_GET_SUCCESS',
    GET_FAILURE: 'TEAM_GET_FAILURE',    

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};
